version: '3.7'

services:
  api:
    build: .
    #container_name: app
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /api
    restart: always
    depends_on:
      - db

  db:
    image: postgres:11
    #container_name: wave_db
    ports:
      - '5432:5432'
    # volumes:
    #   - ./db/postgres/init.d:/docker-entrypoint-initdb.d
    #   - ./db/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root # DB USER
      POSTGRES_PASSWORD: root # DB Password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    hostname: postgres
    user: root
    restart: always
